<?php

namespace app\index\model;

use think\Model;

class User extends Model
{
    //切换数据库
    protected  $connection = 'mysql';

    //数据库的名字
    //protected $name = 'grade';

    //设置主键 ，默认主键为id，你可以设置其他为主键，如uid
    protected $pk = 'id';

    //设置表
    protected $table = 'tp_user';

    //初始化操作做
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //echo "初始化操作";
    }
}